// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_data.proto

package protoData;

public final class StockDataProto {
  private StockDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SingleStockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SingleStock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stock_id = 1;</code>
     * @return The stockId.
     */
    java.lang.String getStockId();
    /**
     * <code>string stock_id = 1;</code>
     * @return The bytes for stockId.
     */
    com.google.protobuf.ByteString
        getStockIdBytes();

    /**
     * <code>string stock_name = 2;</code>
     * @return The stockName.
     */
    java.lang.String getStockName();
    /**
     * <code>string stock_name = 2;</code>
     * @return The bytes for stockName.
     */
    com.google.protobuf.ByteString
        getStockNameBytes();

    /**
     * <code>float stock_price = 3;</code>
     * @return The stockPrice.
     */
    float getStockPrice();

    /**
     * <code>float stock_change = 4;</code>
     * @return The stockChange.
     */
    float getStockChange();
  }
  /**
   * Protobuf type {@code SingleStock}
   */
  public  static final class SingleStock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SingleStock)
      SingleStockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SingleStock.newBuilder() to construct.
    private SingleStock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleStock() {
      stockId_ = "";
      stockName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SingleStock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SingleStock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stockId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stockName_ = s;
              break;
            }
            case 29: {

              stockPrice_ = input.readFloat();
              break;
            }
            case 37: {

              stockChange_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoData.StockDataProto.internal_static_SingleStock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoData.StockDataProto.internal_static_SingleStock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoData.StockDataProto.SingleStock.class, protoData.StockDataProto.SingleStock.Builder.class);
    }

    public static final int STOCK_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object stockId_;
    /**
     * <code>string stock_id = 1;</code>
     * @return The stockId.
     */
    public java.lang.String getStockId() {
      java.lang.Object ref = stockId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockId_ = s;
        return s;
      }
    }
    /**
     * <code>string stock_id = 1;</code>
     * @return The bytes for stockId.
     */
    public com.google.protobuf.ByteString
        getStockIdBytes() {
      java.lang.Object ref = stockId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCK_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object stockName_;
    /**
     * <code>string stock_name = 2;</code>
     * @return The stockName.
     */
    public java.lang.String getStockName() {
      java.lang.Object ref = stockName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockName_ = s;
        return s;
      }
    }
    /**
     * <code>string stock_name = 2;</code>
     * @return The bytes for stockName.
     */
    public com.google.protobuf.ByteString
        getStockNameBytes() {
      java.lang.Object ref = stockName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCK_PRICE_FIELD_NUMBER = 3;
    private float stockPrice_;
    /**
     * <code>float stock_price = 3;</code>
     * @return The stockPrice.
     */
    public float getStockPrice() {
      return stockPrice_;
    }

    public static final int STOCK_CHANGE_FIELD_NUMBER = 4;
    private float stockChange_;
    /**
     * <code>float stock_change = 4;</code>
     * @return The stockChange.
     */
    public float getStockChange() {
      return stockChange_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStockIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stockId_);
      }
      if (!getStockNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stockName_);
      }
      if (stockPrice_ != 0F) {
        output.writeFloat(3, stockPrice_);
      }
      if (stockChange_ != 0F) {
        output.writeFloat(4, stockChange_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStockIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stockId_);
      }
      if (!getStockNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stockName_);
      }
      if (stockPrice_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, stockPrice_);
      }
      if (stockChange_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, stockChange_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoData.StockDataProto.SingleStock)) {
        return super.equals(obj);
      }
      protoData.StockDataProto.SingleStock other = (protoData.StockDataProto.SingleStock) obj;

      if (!getStockId()
          .equals(other.getStockId())) return false;
      if (!getStockName()
          .equals(other.getStockName())) return false;
      if (java.lang.Float.floatToIntBits(getStockPrice())
          != java.lang.Float.floatToIntBits(
              other.getStockPrice())) return false;
      if (java.lang.Float.floatToIntBits(getStockChange())
          != java.lang.Float.floatToIntBits(
              other.getStockChange())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STOCK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStockId().hashCode();
      hash = (37 * hash) + STOCK_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getStockName().hashCode();
      hash = (37 * hash) + STOCK_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStockPrice());
      hash = (37 * hash) + STOCK_CHANGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStockChange());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoData.StockDataProto.SingleStock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoData.StockDataProto.SingleStock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.SingleStock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.SingleStock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoData.StockDataProto.SingleStock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SingleStock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SingleStock)
        protoData.StockDataProto.SingleStockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoData.StockDataProto.internal_static_SingleStock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoData.StockDataProto.internal_static_SingleStock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoData.StockDataProto.SingleStock.class, protoData.StockDataProto.SingleStock.Builder.class);
      }

      // Construct using protoData.StockDataProto.SingleStock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stockId_ = "";

        stockName_ = "";

        stockPrice_ = 0F;

        stockChange_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoData.StockDataProto.internal_static_SingleStock_descriptor;
      }

      @java.lang.Override
      public protoData.StockDataProto.SingleStock getDefaultInstanceForType() {
        return protoData.StockDataProto.SingleStock.getDefaultInstance();
      }

      @java.lang.Override
      public protoData.StockDataProto.SingleStock build() {
        protoData.StockDataProto.SingleStock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoData.StockDataProto.SingleStock buildPartial() {
        protoData.StockDataProto.SingleStock result = new protoData.StockDataProto.SingleStock(this);
        result.stockId_ = stockId_;
        result.stockName_ = stockName_;
        result.stockPrice_ = stockPrice_;
        result.stockChange_ = stockChange_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoData.StockDataProto.SingleStock) {
          return mergeFrom((protoData.StockDataProto.SingleStock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoData.StockDataProto.SingleStock other) {
        if (other == protoData.StockDataProto.SingleStock.getDefaultInstance()) return this;
        if (!other.getStockId().isEmpty()) {
          stockId_ = other.stockId_;
          onChanged();
        }
        if (!other.getStockName().isEmpty()) {
          stockName_ = other.stockName_;
          onChanged();
        }
        if (other.getStockPrice() != 0F) {
          setStockPrice(other.getStockPrice());
        }
        if (other.getStockChange() != 0F) {
          setStockChange(other.getStockChange());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoData.StockDataProto.SingleStock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoData.StockDataProto.SingleStock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object stockId_ = "";
      /**
       * <code>string stock_id = 1;</code>
       * @return The stockId.
       */
      public java.lang.String getStockId() {
        java.lang.Object ref = stockId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stock_id = 1;</code>
       * @return The bytes for stockId.
       */
      public com.google.protobuf.ByteString
          getStockIdBytes() {
        java.lang.Object ref = stockId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stock_id = 1;</code>
       * @param value The stockId to set.
       * @return This builder for chaining.
       */
      public Builder setStockId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stock_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockId() {
        
        stockId_ = getDefaultInstance().getStockId();
        onChanged();
        return this;
      }
      /**
       * <code>string stock_id = 1;</code>
       * @param value The bytes for stockId to set.
       * @return This builder for chaining.
       */
      public Builder setStockIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stockName_ = "";
      /**
       * <code>string stock_name = 2;</code>
       * @return The stockName.
       */
      public java.lang.String getStockName() {
        java.lang.Object ref = stockName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stock_name = 2;</code>
       * @return The bytes for stockName.
       */
      public com.google.protobuf.ByteString
          getStockNameBytes() {
        java.lang.Object ref = stockName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stock_name = 2;</code>
       * @param value The stockName to set.
       * @return This builder for chaining.
       */
      public Builder setStockName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stock_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockName() {
        
        stockName_ = getDefaultInstance().getStockName();
        onChanged();
        return this;
      }
      /**
       * <code>string stock_name = 2;</code>
       * @param value The bytes for stockName to set.
       * @return This builder for chaining.
       */
      public Builder setStockNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockName_ = value;
        onChanged();
        return this;
      }

      private float stockPrice_ ;
      /**
       * <code>float stock_price = 3;</code>
       * @return The stockPrice.
       */
      public float getStockPrice() {
        return stockPrice_;
      }
      /**
       * <code>float stock_price = 3;</code>
       * @param value The stockPrice to set.
       * @return This builder for chaining.
       */
      public Builder setStockPrice(float value) {
        
        stockPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float stock_price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockPrice() {
        
        stockPrice_ = 0F;
        onChanged();
        return this;
      }

      private float stockChange_ ;
      /**
       * <code>float stock_change = 4;</code>
       * @return The stockChange.
       */
      public float getStockChange() {
        return stockChange_;
      }
      /**
       * <code>float stock_change = 4;</code>
       * @param value The stockChange to set.
       * @return This builder for chaining.
       */
      public Builder setStockChange(float value) {
        
        stockChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float stock_change = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockChange() {
        
        stockChange_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SingleStock)
    }

    // @@protoc_insertion_point(class_scope:SingleStock)
    private static final protoData.StockDataProto.SingleStock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoData.StockDataProto.SingleStock();
    }

    public static protoData.StockDataProto.SingleStock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleStock>
        PARSER = new com.google.protobuf.AbstractParser<SingleStock>() {
      @java.lang.Override
      public SingleStock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleStock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleStock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleStock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoData.StockDataProto.SingleStock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AllStockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AllStock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    java.util.List<protoData.StockDataProto.SingleStock> 
        getStockList();
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    protoData.StockDataProto.SingleStock getStock(int index);
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    int getStockCount();
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    java.util.List<? extends protoData.StockDataProto.SingleStockOrBuilder> 
        getStockOrBuilderList();
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    protoData.StockDataProto.SingleStockOrBuilder getStockOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AllStock}
   */
  public  static final class AllStock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AllStock)
      AllStockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AllStock.newBuilder() to construct.
    private AllStock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllStock() {
      stock_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AllStock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AllStock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stock_ = new java.util.ArrayList<protoData.StockDataProto.SingleStock>();
                mutable_bitField0_ |= 0x00000001;
              }
              stock_.add(
                  input.readMessage(protoData.StockDataProto.SingleStock.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          stock_ = java.util.Collections.unmodifiableList(stock_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoData.StockDataProto.internal_static_AllStock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoData.StockDataProto.internal_static_AllStock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoData.StockDataProto.AllStock.class, protoData.StockDataProto.AllStock.Builder.class);
    }

    public static final int STOCK_FIELD_NUMBER = 1;
    private java.util.List<protoData.StockDataProto.SingleStock> stock_;
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    public java.util.List<protoData.StockDataProto.SingleStock> getStockList() {
      return stock_;
    }
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    public java.util.List<? extends protoData.StockDataProto.SingleStockOrBuilder> 
        getStockOrBuilderList() {
      return stock_;
    }
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    public int getStockCount() {
      return stock_.size();
    }
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    public protoData.StockDataProto.SingleStock getStock(int index) {
      return stock_.get(index);
    }
    /**
     * <code>repeated .SingleStock stock = 1;</code>
     */
    public protoData.StockDataProto.SingleStockOrBuilder getStockOrBuilder(
        int index) {
      return stock_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stock_.size(); i++) {
        output.writeMessage(1, stock_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stock_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stock_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoData.StockDataProto.AllStock)) {
        return super.equals(obj);
      }
      protoData.StockDataProto.AllStock other = (protoData.StockDataProto.AllStock) obj;

      if (!getStockList()
          .equals(other.getStockList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStockCount() > 0) {
        hash = (37 * hash) + STOCK_FIELD_NUMBER;
        hash = (53 * hash) + getStockList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoData.StockDataProto.AllStock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.AllStock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoData.StockDataProto.AllStock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoData.StockDataProto.AllStock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.AllStock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoData.StockDataProto.AllStock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoData.StockDataProto.AllStock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllStock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AllStock)
        protoData.StockDataProto.AllStockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoData.StockDataProto.internal_static_AllStock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoData.StockDataProto.internal_static_AllStock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoData.StockDataProto.AllStock.class, protoData.StockDataProto.AllStock.Builder.class);
      }

      // Construct using protoData.StockDataProto.AllStock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStockFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stockBuilder_ == null) {
          stock_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stockBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoData.StockDataProto.internal_static_AllStock_descriptor;
      }

      @java.lang.Override
      public protoData.StockDataProto.AllStock getDefaultInstanceForType() {
        return protoData.StockDataProto.AllStock.getDefaultInstance();
      }

      @java.lang.Override
      public protoData.StockDataProto.AllStock build() {
        protoData.StockDataProto.AllStock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoData.StockDataProto.AllStock buildPartial() {
        protoData.StockDataProto.AllStock result = new protoData.StockDataProto.AllStock(this);
        int from_bitField0_ = bitField0_;
        if (stockBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stock_ = java.util.Collections.unmodifiableList(stock_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stock_ = stock_;
        } else {
          result.stock_ = stockBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoData.StockDataProto.AllStock) {
          return mergeFrom((protoData.StockDataProto.AllStock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoData.StockDataProto.AllStock other) {
        if (other == protoData.StockDataProto.AllStock.getDefaultInstance()) return this;
        if (stockBuilder_ == null) {
          if (!other.stock_.isEmpty()) {
            if (stock_.isEmpty()) {
              stock_ = other.stock_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStockIsMutable();
              stock_.addAll(other.stock_);
            }
            onChanged();
          }
        } else {
          if (!other.stock_.isEmpty()) {
            if (stockBuilder_.isEmpty()) {
              stockBuilder_.dispose();
              stockBuilder_ = null;
              stock_ = other.stock_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stockBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStockFieldBuilder() : null;
            } else {
              stockBuilder_.addAllMessages(other.stock_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoData.StockDataProto.AllStock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoData.StockDataProto.AllStock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protoData.StockDataProto.SingleStock> stock_ =
        java.util.Collections.emptyList();
      private void ensureStockIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stock_ = new java.util.ArrayList<protoData.StockDataProto.SingleStock>(stock_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoData.StockDataProto.SingleStock, protoData.StockDataProto.SingleStock.Builder, protoData.StockDataProto.SingleStockOrBuilder> stockBuilder_;

      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public java.util.List<protoData.StockDataProto.SingleStock> getStockList() {
        if (stockBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stock_);
        } else {
          return stockBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public int getStockCount() {
        if (stockBuilder_ == null) {
          return stock_.size();
        } else {
          return stockBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public protoData.StockDataProto.SingleStock getStock(int index) {
        if (stockBuilder_ == null) {
          return stock_.get(index);
        } else {
          return stockBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder setStock(
          int index, protoData.StockDataProto.SingleStock value) {
        if (stockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStockIsMutable();
          stock_.set(index, value);
          onChanged();
        } else {
          stockBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder setStock(
          int index, protoData.StockDataProto.SingleStock.Builder builderForValue) {
        if (stockBuilder_ == null) {
          ensureStockIsMutable();
          stock_.set(index, builderForValue.build());
          onChanged();
        } else {
          stockBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder addStock(protoData.StockDataProto.SingleStock value) {
        if (stockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStockIsMutable();
          stock_.add(value);
          onChanged();
        } else {
          stockBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder addStock(
          int index, protoData.StockDataProto.SingleStock value) {
        if (stockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStockIsMutable();
          stock_.add(index, value);
          onChanged();
        } else {
          stockBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder addStock(
          protoData.StockDataProto.SingleStock.Builder builderForValue) {
        if (stockBuilder_ == null) {
          ensureStockIsMutable();
          stock_.add(builderForValue.build());
          onChanged();
        } else {
          stockBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder addStock(
          int index, protoData.StockDataProto.SingleStock.Builder builderForValue) {
        if (stockBuilder_ == null) {
          ensureStockIsMutable();
          stock_.add(index, builderForValue.build());
          onChanged();
        } else {
          stockBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder addAllStock(
          java.lang.Iterable<? extends protoData.StockDataProto.SingleStock> values) {
        if (stockBuilder_ == null) {
          ensureStockIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stock_);
          onChanged();
        } else {
          stockBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder clearStock() {
        if (stockBuilder_ == null) {
          stock_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stockBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public Builder removeStock(int index) {
        if (stockBuilder_ == null) {
          ensureStockIsMutable();
          stock_.remove(index);
          onChanged();
        } else {
          stockBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public protoData.StockDataProto.SingleStock.Builder getStockBuilder(
          int index) {
        return getStockFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public protoData.StockDataProto.SingleStockOrBuilder getStockOrBuilder(
          int index) {
        if (stockBuilder_ == null) {
          return stock_.get(index);  } else {
          return stockBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public java.util.List<? extends protoData.StockDataProto.SingleStockOrBuilder> 
           getStockOrBuilderList() {
        if (stockBuilder_ != null) {
          return stockBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stock_);
        }
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public protoData.StockDataProto.SingleStock.Builder addStockBuilder() {
        return getStockFieldBuilder().addBuilder(
            protoData.StockDataProto.SingleStock.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public protoData.StockDataProto.SingleStock.Builder addStockBuilder(
          int index) {
        return getStockFieldBuilder().addBuilder(
            index, protoData.StockDataProto.SingleStock.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleStock stock = 1;</code>
       */
      public java.util.List<protoData.StockDataProto.SingleStock.Builder> 
           getStockBuilderList() {
        return getStockFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoData.StockDataProto.SingleStock, protoData.StockDataProto.SingleStock.Builder, protoData.StockDataProto.SingleStockOrBuilder> 
          getStockFieldBuilder() {
        if (stockBuilder_ == null) {
          stockBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protoData.StockDataProto.SingleStock, protoData.StockDataProto.SingleStock.Builder, protoData.StockDataProto.SingleStockOrBuilder>(
                  stock_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stock_ = null;
        }
        return stockBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AllStock)
    }

    // @@protoc_insertion_point(class_scope:AllStock)
    private static final protoData.StockDataProto.AllStock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoData.StockDataProto.AllStock();
    }

    public static protoData.StockDataProto.AllStock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllStock>
        PARSER = new com.google.protobuf.AbstractParser<AllStock>() {
      @java.lang.Override
      public AllStock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllStock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllStock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllStock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoData.StockDataProto.AllStock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleStock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingleStock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllStock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllStock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020stock_data.proto\"^\n\013SingleStock\022\020\n\010sto" +
      "ck_id\030\001 \001(\t\022\022\n\nstock_name\030\002 \001(\t\022\023\n\013stock" +
      "_price\030\003 \001(\002\022\024\n\014stock_change\030\004 \001(\002\"\'\n\010Al" +
      "lStock\022\033\n\005stock\030\001 \003(\0132\014.SingleStockB\033\n\tp" +
      "rotoDataB\016StockDataProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SingleStock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SingleStock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingleStock_descriptor,
        new java.lang.String[] { "StockId", "StockName", "StockPrice", "StockChange", });
    internal_static_AllStock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AllStock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllStock_descriptor,
        new java.lang.String[] { "Stock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
